# Generated by Django 3.2.7 on 2022-01-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_of_place', models.CharField(max_length=50)),
                ('is_ticket_required', models.BooleanField(default=False)),
                ('adult_ticket', models.PositiveIntegerField(default=0)),
                ('child_ticket', models.PositiveIntegerField(default=0)),
                ('number_of_ratings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('attractions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='app.attractions')),
            ],
        ),
        migrations.AddField(
            model_name='attractions',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='app.city'),
        ),
    ]
